### ISSUE TITLE
Schedule Wars

### ISSUE THREAD

**Issue by magnetomage** [utoxin/TimTheWordWarBot#17]
It would be helpful to be able to Schedule Word wars to an exact time (I.e. 8:45 Am, 4:00 pm, 23:45 etc.) . I would suggest that you limit the start times to something reasonable. (say within a few hours) so as to not put undue pressure on the hosting resources.

**Comment by utoxin** [comment]
Agreed. :) I'll probably implement something like that in the re-write of Timmy.

**Comment by utoxin** [comment]
So. I've been thinking about this. And.... uh.... timezones.

**Comment by utoxin** [comment]
Done. The 'at:<time>' syntax is now supported in wars.
