### ISSUE TITLE
Submitting war report in PM crashes the bot

### ISSUE THREAD

**Issue by utoxin** [utoxin/TimTheWordWarBot#58]
**Describe the bug**
Submitting a war report in a PM tries to access channel war data, which doesn't exist for PMs. These needs a safety check.

**Comment by magnetomage** [comment]
including the war id crashes as well

**Comment by utoxin** [comment]
Nope, that is still exactly correct. He accesses that channel data regardless, for a couple things. I'm re-structuring to prevent that now.
